### ISSUE TITLE
broken in second February update

### ISSUE THREAD

**Issue by Splerge** [glua/gm_roc#3]
client crashes when you join servers

**Comment by meepdarknessmeep** [comment]
:box:

**Comment by Splerge** [comment]
tru

**Comment by Leystryku** [comment]
The module hooked 3 functions in an attempt to hook one function, aka remake it

**Comment by LennyPenny** [comment]
Well I actually want it to hook 2, idk how to get around hooking the first

**Comment by SwadicalRag** [comment]
hooking and blackjack

**Comment by CaptainPRICE** [comment]
It is actually fk up even more in April update. This needs rewriting. Some info to start with:
CLuaInterface vtable has been changed, but CLuaShared vtable did not change (at least it seems to be unchanged; from what I see in my dump-diff). RunStringEx vfunc is now at index `111`..

**Comment by meepdarknessmeep** [comment]
Ok

**Comment by LennyPenny** [comment]
This needs to be rewritten because an index changed? hm
Seems like you already got the answers tho, maybe make a pr

**Comment by SwadicalRag** [comment]
its joke man
haha
XZDDDDDDDDDDDDDDDD

how 2 lau plz plox XD

**Comment by SwadicalRag** [comment]
oh man i am nor good with computter

how do i do deeze

oh m**AN**

**Comment by SwadicalRag** [comment]
welcoem to SHIT mEME HOUR

![SHTI MEME](http://i.imgur.com/j2wg6Dq.png)

**Comment by SwadicalRag** [comment]
DO U HAVE A MOMENT TO TALK ABOUT ORU

LORD
AND
SAVIOUR

SIGSCANNING?

**Comment by LennyPenny** [comment]
>caring enough about gmod hax to create a sig

**Comment by SwadicalRag** [comment]
nice meme

**Comment by SwadicalRag** [comment]
test comment please ignore

**Comment by SwadicalRag** [comment]
woohoo it works
![](https://cdn.discordapp.com/attachments/152162730244177920/304936760494784512/image.png)

**Comment by mcd1992** [comment]
fake and gay

**Comment by LennyPenny** [comment]
cheers @CaptainPRICE just had to change the index to 111 and it works fine again. 

Next time just make a PR to get your name into the greatest most advanced hacking tool in history
