### ISSUE TITLE
This function doesn't even documented. Does it still exists anywhere?

### ISSUE THREAD

**Issue by uRandomAlex** [glua/gm_roc#4]
This function doesn't even documented. Does it still exists anywhere?

**Comment by gspetrou** [comment]
It doesn't exist, that's why this addon bring it back.

**Comment by HandsomeMatt** [comment]
good thread

**Comment by SwadicalRag** [comment]
This thread doesn't even good. Does it still memes anywhere?

**Comment by birdbrainswagtrain** [comment]
javascript

**Comment by Splerge** [comment]
👌👌👌👌👌👌

On Friday, May 13, 2016, Adam Coggeshall <notifications@github.com> wrote:

> javascript
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/glua/gm_roc/issues/4#issuecomment-218823879>
>


-- 
--

**Comment by SwadicalRag** [comment]
:factory: :factory: :factory: :factory: :factory: :factory: :factory: :factory: 
:factory: we need to build a wall :factory: 
:factory: :factory: :factory: :factory: :factory: :factory: :factory: :factory:

**Comment by birdbrainswagtrain** [comment]
Do we need to build a wall to keep javascript out?

**Comment by PotcFdk** [comment]
Make scripting great again.

**Comment by mcd1992** [comment]
And we'll make Guido van Rossum pay for the wall!

**Comment by birdbrainswagtrain** [comment]
Just realized that I have an irrational hatred of python.
# :us: _**BUILD THE WALL**_ :us:

**Comment by PotcFdk** [comment]
All in all we're just another brick in the wall.

**Comment by SwadicalRag** [comment]
:OK_hand:
