### ISSUE TITLE
RunOnClient

### ISSUE THREAD

**Issue by MalboroGmod** [glua/gm_roc#6]
RunOnClient( [[ print( "toto" ) ]] ) crash my game.

**Comment by mcd1992** [comment]
Install gentoo.

**Comment by MalboroGmod** [comment]
Why ?

**Comment by birdbrainswagtrain** [comment]
Install javascript.

**Comment by MalboroGmod** [comment]
Install Garry's Mod ?

**Comment by PotcFdk** [comment]
>Install gentoo.

[![Install Gentoo](https://img.youtube.com/vi/VjGSMUep6_4/0.jpg)](https://www.youtube.com/watch?v=VjGSMUep6_4)

**Comment by meepdarknessmeep** [comment]
install gentoo

**Comment by mcd1992** [comment]
:late: as always meep

**Comment by SpencerSharkey** [comment]
gentoo lol

**Comment by LennyPenny** [comment]
I love sunos
