### ISSUE TITLE
RunOnClient does not work

### ISSUE THREAD

**Issue by HappyDOGE** [glua/gm_roc#7]
Hello.
When I am trying to use RunOnClient, it crashes the game.
I checked everything.

**Comment by LennyPenny** [comment]
Did you build the latest commit from 15 days ago?

**Comment by HappyDOGE** [comment]
of course

**Comment by LennyPenny** [comment]
Was there an update that changed the offsets within the timeframe?

**Comment by HappyDOGE** [comment]
Well, there was an update which removes ILuaInterface

**Comment by HappyDOGE** [comment]
Also, there was simillar issue [HERE](https://github.com/glua/gm_roc/issues/6)

**Comment by LennyPenny** [comment]
That issue was irrelevant
If ILuaInterface was removed there is no bringing this back easily, would have to be a rewrite

**Comment by HappyDOGE** [comment]
Also, when I run code like that: 
```RunOnClient(argStr,"","lua/includes/init.lua")```
```
] lua_run_client print("lol")

[ERROR] print("lol"):1: '=' expected near '/'
  1. unknown - print("lol"):0
```

**Comment by HappyDOGE** [comment]
Ok, I fixed the problem by using ```RunOnClient("lua/includes/init.lua","",argStr)``` .

**Comment by SwadicalRag** [comment]
ok

**Comment by meepdarknessmeep** [comment]
autism
