### ISSUE TITLE
Access violation when calling RunOnClient

### ISSUE THREAD

**Issue by half-cambodian-hacker-man** [glua/gm_roc#8]
When I call RunOnClient from the menu state, (while in a singleplayer instance), hl2.exe crashes and produces a minidump (I can upload it, if needed, on request)
The exception produced is an access violation.

However, the hook for RunOnClient seems to fire just fine, so it isn't a problem with hooking the function.

**Comment by half-cambodian-hacker-man** [comment]
I'm an idiot, I was calling the function with incorrect parameters.

Maybe write a failsafe so that it doesn't crash?

**Comment by SwadicalRag** [comment]
seasonal greetings from glua.team

that's a feature not a bug
